"""
Visualization Styling & Formatting Utilities
============================================
Shared primitives for standardizing chart aesthetics and axis formatting.

Purpose
-------
This module provides a centralized toolkit for applying a consistent visual
identity to all plots generated by the platform. It ensures that charts
are professional, readable, and adhere to institutional reporting standards.

Usage
-----
Intended for internal use by other visualization modules.

.. code-block:: python

    from matplotlib.ticker import FuncFormatter
    from .utils import set_style, format_currency

    # Apply global style at the start of a plotting function
    set_style()
    
    # Use formatter for an axis
    plt.gca().yaxis.set_major_formatter(FuncFormatter(format_currency))

Importance
----------
-   **Visual Consistency**: `set_style` ensures all charts share the same theme,
    font sizes, and line weights, creating a cohesive look for tearsheets.
-   **Readability**: `format_currency` transforms large numerical values (e.g.,
    1,500,000) into human-readable strings (e.g., "$1.5M"), improving the
    clarity of equity curves and financial reports.

Tools & Frameworks
------------------
-   **Matplotlib**: Core library for setting global `rcParams` and axis formatters.
-   **Seaborn**: Used to apply high-level aesthetic themes (e.g., "whitegrid").
"""

import matplotlib.pyplot as plt
import seaborn as sns

def set_style():
    """
    Applies a global, project-wide plotting style using Seaborn and Matplotlib.
    
    This function establishes a consistent visual theme ("whitegrid") and sets
    default figure sizes, font sizes, and line widths to ensure uniformity
    across all generated charts and reports.
    """
    sns.set_theme(style="whitegrid")
    plt.rcParams['figure.figsize'] = (12, 6)
    plt.rcParams['axes.titlesize'] = 14
    plt.rcParams['axes.labelsize'] = 12
    plt.rcParams['lines.linewidth'] = 1.5

def format_currency(x, pos):
    """
    Formatter function for Matplotlib axes to display numbers as currency.
    
    Converts large numeric values into a compact, human-readable string format
    with suffixes for Thousands (K), Millions (M), and Billions (B).
    
    Args:
        x (float): The numeric value from the axis tick.
        pos (int): The position of the tick. Required by the `FuncFormatter` 
                   interface but unused in this implementation.
                   
    Returns:
        str: A formatted string (e.g., "$1.5M", "$250K").
    """
    sign = '-' if x < 0 else ''
    x = abs(x)
    
    if x >= 1e9:
        return f'{sign}${x*1e-9:1.1f}B'
    elif x >= 1e6:
        return f'{sign}${x*1e-6:1.1f}M'
    elif x >= 1e3:
        return f'{sign}${x*1e-3:1.0f}K'
    return f'{sign}${x:1.0f}'